import JSZip from 'jszip'
import type { Creation } from './types'

function appModule(code: string) {
  const withoutMount = code.replace(/ReactDOM\.createRoot\([\s\S]*?\.render\(<[A-Z][A-Za-z0-9_]*\s*\/>\);?/g, '').trim()
  const component = withoutMount.match(/function\s+([A-Z][A-Za-z0-9_]*)\s*\(/)?.[1] ?? 'App'
  return `${withoutMount}\nexport default ${component};\n`
}

export async function exportCreationZip(creation: Creation) {
  const zip = new JSZip()
  const slug = creation.title.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'alphatekx-creation'
  zip.file('src/App.jsx', appModule(creation.code))
  zip.file('src/main.jsx', "import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\nReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);\n")
  zip.file('src/index.css', 'html,body,#root{min-height:100%;margin:0}*{box-sizing:border-box}body{font-family:Inter,ui-sans-serif,system-ui,sans-serif}')
  zip.file('index.html', '<!doctype html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>AlphaTekX Creation</title><script src="https://cdn.tailwindcss.com"></script></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>')
  zip.file('vite.config.js', "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({plugins:[react()]});\n")
  zip.file('package.json', JSON.stringify({ name:slug, private:true, version:'1.0.0', type:'module', scripts:{dev:'vite',build:'vite build',preview:'vite preview'}, dependencies:{'@vitejs/plugin-react':'latest',vite:'latest',react:'^18.3.1','react-dom':'^18.3.1'} }, null, 2))
  zip.file('.env.example', '# Add service credentials required by your creation here.\n')
  zip.file('vercel.json', JSON.stringify({ rewrites:[{source:'/(.*)',destination:'/index.html'}] }, null, 2))
  zip.file('Dockerfile', 'FROM node:20-alpine AS build\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nRUN npm run build\nFROM nginx:alpine\nCOPY --from=build /app/dist /usr/share/nginx/html\nCOPY nginx.conf /etc/nginx/conf.d/default.conf\nEXPOSE 80\n')
  zip.file('nginx.conf', 'server { listen 80; root /usr/share/nginx/html; index index.html; location / { try_files $uri $uri/ /index.html; } }\n')
  zip.file('README.md', `# ${creation.title}\n\nGenerated by AlphaTekX God Craft OS.\n\n## Run\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Deploy\n\n[Deploy with Vercel](https://vercel.com/new/clone?repository-url=YOUR_GITHUB_REPOSITORY_URL)\n`)
  const blob = await zip.generateAsync({ type:'blob' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href=url; anchor.download=`${slug}.zip`; anchor.click(); URL.revokeObjectURL(url)
}
