import { useState } from 'react'
import { ArrowRight, Check, Code2, MessageSquare, Rocket } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'

export default function Landing() {
  const [prompt, setPrompt] = useState('')
  const navigate = useNavigate()
  const build = () => { if (!prompt.trim()) return; try { localStorage.setItem('alphatekx-draft', prompt.trim()) } catch {}; navigate('/auth') }
  return <div className="min-h-screen bg-white text-[#111111]">
    <nav className="sticky top-0 z-30 border-b border-gray-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 md:px-8"><Link to="/" className="text-sm font-semibold tracking-[0.14em]">ALPHATEKX</Link><div className="flex items-center gap-2"><Link to="/auth" className="min-h-10 rounded-lg px-4 py-2.5 text-sm">Log in</Link><Link to="/auth" className="min-h-10 rounded-lg bg-black px-4 py-2.5 text-sm font-medium text-white">Start building</Link></div></div></nav>
    <main>
      <section className="mx-auto flex min-h-[620px] max-w-5xl items-center px-5 py-20 text-center md:px-8"><div className="w-full"><p className="text-sm font-medium text-gray-500">AI software builder</p><h1 className="mx-auto mt-4 max-w-3xl text-4xl font-semibold tracking-tight md:text-6xl">Build anything with AI</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-gray-600">Describe what you need. Alpha helps you plan, build, improve, and launch it in one place.</p><div className="mx-auto mt-8 flex max-w-2xl flex-col gap-2 rounded-xl border border-gray-300 bg-white p-2 shadow-sm sm:flex-row"><input value={prompt} onChange={event => setPrompt(event.target.value)} onKeyDown={event => event.key === 'Enter' && build()} className="min-h-12 min-w-0 flex-1 px-3 outline-none" placeholder="Build a school website, create a store..."/><button onClick={build} className="flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-lg bg-black px-5 text-sm font-medium text-white" type="button">Start <ArrowRight size={16}/></button></div></div></section>
      <section className="border-y border-gray-200 bg-[#FAFAFA]"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 md:grid-cols-3 md:px-8">{[[MessageSquare,'1. Type your idea','Use your own words. No technical knowledge needed.'],[Code2,'2. Chat with AI','Answer simple questions and watch your product take shape.'],[Rocket,'3. Publish and launch','Review the result, then share it with the world.']].map(([Icon,title,text]) => { const FeatureIcon = Icon as typeof MessageSquare; return <article key={String(title)}><FeatureIcon size={20}/><h2 className="mt-4 text-xl font-semibold">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-gray-600">{String(text)}</p></article> })}</div></section>
      <section className="mx-auto max-w-6xl px-5 py-20 md:px-8"><div className="grid gap-10 md:grid-cols-2"><div><h2 className="text-2xl font-semibold">One simple workspace</h2><p className="mt-3 max-w-lg text-sm leading-6 text-gray-600">Keep every idea as a mission. Chat with Alpha, see your app, save useful creations, and launch when you are ready.</p><Link to="/auth" className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-lg bg-black px-5 text-sm font-medium text-white">Open workspace <ArrowRight size={16}/></Link></div><div className="rounded-xl border border-gray-200 bg-[#FAFAFA] p-6 shadow-sm"><p className="text-sm font-semibold">What Alpha can help with</p><ul className="mt-4 space-y-3 text-sm text-gray-600">{['Build websites and web apps','Teach a subject step by step','Create reusable AI helpers','Publish and launch your work'].map(item => <li key={item} className="flex items-center gap-3"><Check size={16} className="text-black"/>{item}</li>)}</ul></div></div></section>
      <section className="border-t border-gray-200 bg-[#FAFAFA] px-5 py-16 text-center"><h2 className="text-2xl font-semibold">What will you build today?</h2><p className="mt-3 text-sm text-gray-600">Start free and turn your next idea into something real.</p><Link to="/auth" className="mt-6 inline-flex min-h-12 items-center rounded-lg bg-black px-6 text-sm font-medium text-white">Start building</Link></section>
    </main>
    <footer className="border-t border-gray-200 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-5 py-10 text-sm text-gray-500 md:flex-row md:items-center md:justify-between md:px-8"><strong className="text-gray-900">AlphaTekx</strong><span>Build anything with AI · © 2026 AlphaTekx</span><div className="flex gap-4"><a href="mailto:hello@alphatekx.name.ng">Contact</a><Link to="/auth">Workspace</Link></div></div></footer>
  </div>
}
