import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, Check, Code2, Globe2, Layers3, Rocket, Sparkles, Wand2, Zap } from 'lucide-react'
import { motion } from 'framer-motion'

const apps = ['Translator', 'CRM', 'Todo', 'Blog', 'Landing Page', 'AI Chat', 'E-commerce']
const features = [
  ['Instant Deploy', 'Go from prompt to a live URL in seconds.', Rocket], ['Full Code Ownership', 'Your code stays yours. Export and extend it.', Code2],
  ['Real React + Vite', 'Production foundations, not static mockups.', Layers3], ['Custom Domains', 'Put your product on a domain you own.', Globe2],
  ['No Limits', 'Build, iterate, and ship as often as you need.', Zap], ['Built for Founders', 'Move from insight to execution without friction.', Wand2],
] as const

export default function Landing() {
  const [prompt, setPrompt] = useState('')
  const navigate = useNavigate()
  const build = () => { if (!prompt.trim()) return; try { localStorage.setItem('alphatekx-draft', prompt.trim()) } catch {}; navigate(`/builder?prompt=${encodeURIComponent(prompt.trim())}`) }
  return <div className="min-h-screen overflow-hidden bg-black text-white">
    <nav className="fixed inset-x-0 top-0 z-30 border-b border-white/10 bg-black/70 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10">
      <Link to="/" className="text-lg font-bold tracking-[0.22em]">ALPHATEK<span className="text-[#FFD700]">X</span></Link>
      <div className="hidden items-center gap-8 text-sm text-white/60 md:flex"><a href="#features">Features</a><a href="#showcase">Showcase</a><a href="#pricing">Pricing</a></div>
      <div className="flex items-center gap-3"><Link to="/home" className="hidden rounded-full px-4 py-2 text-sm text-white/70 hover:text-white sm:block">Login</Link><Link to="/builder" className="rounded-full bg-[#FFD700] px-5 py-2.5 text-sm font-bold text-black">Start Building</Link></div>
    </div></nav>
    <main>
      <section className="relative flex min-h-[760px] items-center justify-center px-6 pt-28 text-center"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_35%,rgba(255,215,0,.14),transparent_35%)]"/><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} className="relative max-w-5xl"><p className="mb-8 text-xs font-semibold uppercase tracking-[0.35em] text-[#FFD700]">The AI engineer for ambitious ideas</p><h1 className="text-5xl font-semibold tracking-[-0.06em] md:text-8xl">Turn Your Idea<br/><span className="text-white/45">Into Reality</span></h1><p className="mx-auto mt-8 max-w-2xl text-lg leading-8 text-white/55">AlphaTekx is the AI engineer that builds your app in 30 seconds. From prompt to deployed product.</p><div className="mx-auto mt-10 flex max-w-3xl rounded-2xl border border-[#FFD700]/50 bg-white/[0.06] p-2 shadow-[0_0_60px_rgba(255,215,0,.12)]"><input value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&build()} className="min-w-0 flex-1 bg-transparent px-5 py-4 text-white outline-none placeholder:text-white/30" placeholder="Describe the app you want to build..."/><button onClick={build} className="flex shrink-0 items-center gap-2 rounded-xl bg-[#FFD700] px-6 py-3 font-bold text-black">Build Now <ArrowRight size={17}/></button></div><p className="mt-4 text-xs text-white/35">⚡ Live: 1597 modules built in 2.83s · Deployed on alphatekx.name.ng</p></motion.div></section>
      <section id="showcase" className="border-y border-white/10 py-6"><div className="flex min-w-max animate-[marquee_25s_linear_infinite] gap-10 text-sm text-white/40">{[...apps,...apps].map((a,i)=><span key={i} className="flex items-center gap-3">✦ {a}</span>)}</div></section>
      <section className="mx-auto max-w-7xl px-6 py-28 lg:px-10"><div className="mb-10 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[0.3em] text-[#FFD700]">Live build demo</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">From thought to product.</h2></div><span className="rounded-full border border-emerald-400/30 px-4 py-2 text-xs text-emerald-300">● Built live on Render</span></div><div className="grid overflow-hidden rounded-3xl border border-white/10 bg-white/[0.04] lg:grid-cols-2"><div className="p-8 font-mono text-sm leading-8 text-white/35"><p className="text-[#FFD700]">// AlphaTekx is building</p>{['const [languages, setLanguages] = useState([])', 'const [history, setHistory] = useState([])', 'const translate = async (text) => {', '  setHistory(prev => [result, ...prev])', '}', 'return <TranslatorApp />'].map((line,i)=><p key={i}><span className="mr-5 text-white/20">0{i+1}</span>{line}</p>)}<div className="mt-8 h-1 w-32 animate-pulse bg-[#FFD700]"/></div><div className="min-h-[330px] bg-white p-8 text-black"><div className="mx-auto max-w-sm"><div className="flex items-center justify-between"><b>🌐 Translator</b><span className="text-xs text-black/40">EN → ES</span></div><div className="mt-8 rounded-2xl bg-slate-100 p-5 text-sm text-slate-400">Type anything to translate...</div><button className="mt-4 w-full rounded-xl bg-black py-3 text-sm font-bold text-white">Translate</button><div className="mt-8 border-t pt-5 text-xs text-black/40">Translation history · 12 saved</div></div></div></div></section>
      <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="grid gap-12 md:grid-cols-3"><div><p className="text-xs text-[#FFD700]">01</p><h3 className="mt-4 text-2xl font-semibold">Prompt</h3><p className="mt-3 text-white/45">Tell AlphaTekx what you want in plain language.</p></div><div><p className="text-xs text-[#FFD700]">02</p><h3 className="mt-4 text-2xl font-semibold">Build</h3><p className="mt-3 text-white/45">AI builds pages, components, logic, and data flows.</p></div><div><p className="text-xs text-[#FFD700]">03</p><h3 className="mt-4 text-2xl font-semibold">Ship</h3><p className="mt-3 text-white/45">Deploy instantly to your domain and keep iterating.</p></div></div></section>
      <section id="features" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs uppercase tracking-[0.3em] text-[#FFD700]">The standard</p><h2 className="mt-4 text-4xl font-semibold">Everything you need to move.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-3">{features.map(([title,desc,Icon])=><article key={title} className="bg-black p-8"><Icon className="text-[#FFD700]" size={22}/><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{desc}</p></article>)}</div></section>
      <section id="pricing" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><h2 className="text-center text-4xl font-semibold">Simple, serious pricing.</h2><div className="mt-12 grid gap-5 lg:grid-cols-3">{[['Starter','$0','5 builds / month','Community support'],['Pro','$29','Unlimited builds','Custom domain · Export code'],['Empire','$99','Team workspace','API · Priority · White-label']].map(([name,price,one,two],i)=><article key={name} className={`rounded-3xl border p-8 ${i===1?'border-[#FFD700] bg-[#FFD700] text-black':'border-white/10 bg-white/[0.04]'}`}><p className="text-sm font-semibold">{name}</p><p className="mt-8 text-5xl font-semibold">{price}<span className="text-sm font-normal opacity-50">/mo</span></p><div className="mt-8 space-y-3 text-sm opacity-70"><p><Check size={15} className="mr-2 inline"/>{one}</p><p><Check size={15} className="mr-2 inline"/>{two}</p></div><button onClick={()=>navigate('/builder')} className={`mt-10 w-full rounded-full py-3 text-sm font-bold ${i===1?'bg-black text-white':'bg-white text-black'}`}>Choose {name}</button></article>)}</div></section>
      <section className="mx-6 rounded-3xl bg-gradient-to-br from-[#FFD700] to-[#a47b00] px-6 py-24 text-center text-black lg:mx-auto lg:max-w-7xl"><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">Your idea is worth billions.<br/>Build it now.</h2><Link to="/builder" className="mt-10 inline-flex items-center gap-2 rounded-full bg-black px-7 py-4 font-bold text-white">Start Building Free <ArrowRight size={17}/></Link></section>
    </main><footer className="mx-auto flex max-w-7xl flex-col gap-6 px-6 py-16 text-sm text-white/40 md:flex-row md:items-center md:justify-between lg:px-10"><span className="font-bold tracking-[0.2em] text-white">ALPHATEK<span className="text-[#FFD700]">X</span></span><span>Turn Your Idea Into Reality · © 2026 AlphaTekx Inc.</span><div className="flex gap-5"><a href="#features">Features</a><a href="#pricing">Pricing</a><Link to="/home">Login</Link></div></footer>
  </div>
}
